[project]
name = "fly-in"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YuriASN", email = "yuriasn@hotmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "colorama>=0.4.6",
    "pandas>=2.3.3",
    "pydantic>=2.13.5",
    "types-colorama>=0.4.15.20260508",
    "typing>=3.10.0.0",
]

[project.scripts]
fly-in = "fly_in:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
